USE app_meditaciones; 

-- CREACIÓN DE VISTAS

-- VISTA 1: Muestra el nombre y apellido del usuario y la suscripción contratada
-- los datos se extraen de las tablas usuarios y suscripciones
CREATE OR REPLACE  VIEW VW_USUARIOS_SUSCRIPCIONES AS
SELECT U.NOMBRE, U.APELLIDO, S.NOMBRE AS SUSCRIPCION
FROM USUARIOS AS U
JOIN SUSCRIPCIONES AS S ON U.ID_SUSCRIPCION = S.ID_SUSCRIPCION;

SELECT * FROM VW_USUARIOS_SUSCRIPCIONES;

-- VISTA 2: Muestra las meditaciones junto con sus valoraciones y comentarios, pero solo muestra las que tienen una valoración igual a 'BUENA'
-- los datos se extraen de las tablas meditaciones y valoraciones. 
CREATE OR REPLACE  VIEW VW_MEDITACIONES_VALORACIONES_BUENAS AS
SELECT M.NOMBRE AS MEDITACION, V.VALORACION, V.COMENTARIO
FROM MEDITACIONES AS M
JOIN VALORACIONES AS V ON M.ID_VALORACION = V.ID_VALORACION
WHERE V.VALORACION = 'BUENA';

SELECT * FROM VW_MEDITACIONES_VALORACIONES_BUENAS;

-- VISTA 3: Muestra la valoración máxima que ha obtenido cada una de las meditaciones
-- Los datos de extraen de las tablas meditaciones y valoraciones. 
CREATE OR REPLACE  VIEW VW_MEDITACIONES_VALORACIONES_MAXIMAS AS
SELECT M.NOMBRE AS MEDITACION, MAX(V.VALORACION) AS VALORACION_MAXIMA
FROM
MEDITACIONES AS M
LEFT JOIN VALORACIONES AS V ON M.ID_VALORACION = V.ID_VALORACION
GROUP BY M.NOMBRE;

SELECT * FROM VW_MEDITACIONES_VALORACIONES_MAXIMAS;

-- VISTA 4: Muestra la cantidad de usuarios que contrataron cada uno de los tipos de suscripciones
-- Los datos de extraen de las tablas suscripciones y usuarios. 
CREATE OR REPLACE VIEW  VW_SUSCRIPCIONES_USUARIOS_CANTIDAD AS
SELECT S.NOMBRE AS SUSCRIPCION, COUNT(U.ID_USUARIO) AS CANTIDAD_USUARIOS
FROM
SUSCRIPCIONES AS S
LEFT JOIN USUARIOS AS U ON S.ID_SUSCRIPCION = U.ID_SUSCRIPCION
GROUP BY S.NOMBRE
ORDER BY COUNT(U.ID_USUARIO) DESC;

SELECT * FROM VW_SUSCRIPCIONES_USUARIOS_CANTIDAD;

-- VISTA 5: Muestra los 3 usuarios que han pasado más tiempo meditando
-- Los datos de extraen de las tablas usuarios y estadisticas.
CREATE OR REPLACE VIEW  VW_USUSARIOS_MAYOR_TIEMPO_MEDITANDO AS
SELECT U.NOMBRE, U.APELLIDO, E.TOTAL AS TIEMPO_TOTAL_MEDITANDO
FROM USUARIOS AS U
JOIN ESTADISTICAS AS E ON U.ID_ESTADISTICA = E.ID_ESTADISTICA
ORDER BY E.TOTAL DESC
LIMIT 3;

SELECT * FROM VW_USUSARIOS_MAYOR_TIEMPO_MEDITANDO;


