USE app_meditaciones;

-- TABLA DE LOG DE INSERCIONES: REGISTRA INFORMACIÓN SOBRE LAS INSERCIONES DE DATOS EN OTRAS TABLAS DE LA BASE DE DATOS 
DROP TABLE IF EXISTS LOG_INSERCIONES;
CREATE TABLE IF NOT EXISTS LOG_INSERCIONES (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TABLA VARCHAR(50) NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL
);

-- TABLA DE LOG DE MODIFICACIONES: REGISTRA INFORMACIÓN DETALLADA SOBRE LAS MODIFICACIONES REALIZADAS EN OTRAS TABLAS DE LA BASE DE DATOS
DROP TABLE IF EXISTS LOG_MODIFICACIONES;
CREATE TABLE IF NOT EXISTS LOG_MODIFICACIONES (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TABLA VARCHAR(50) NOT NULL,
    ID_REGISTRO INT NOT NULL,
    DESCRIPCION_ANTERIOR VARCHAR(255),
    DESCRIPCION_ACTUAL VARCHAR(255),
    USUARIO_MODIFICADOR VARCHAR(50) NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    HORA_MODIFICACION TIME NOT NULL
);

-- TRIGGER BEFORE PARA ESTADISTICAS: SE ACTIVA ANTES DE REALIZAR UNA INSERCIÓN EN LA TABLA ESTADISTICAS Y REGISTRA EN LA TABLA LOG_INSERCIONES
-- EL NOMBRE DE LA TABLA DONDE SE INSERTÓ EL REGISTRO, EL USUARIO QUE REALIZÓ LA INSERCIÓN Y LA FECHA Y HORA DE LA INSERCIÓN.
DROP TRIGGER IF EXISTS TRG_LOG_ESTADISTICAS_BEFORE;
DELIMITER $$
CREATE TRIGGER TRG_LOG_ESTADISTICAS_BEFORE
BEFORE INSERT ON ESTADISTICAS
FOR EACH ROW
BEGIN
    INSERT INTO LOG_INSERCIONES (NOMBRE_TABLA, USUARIO, FECHA, HORA)
    VALUES ('ESTADISTICAS', USER(), CURDATE(), CURTIME());
END;
$$
DELIMITER ;

-- TRIGGER AFTER PARA ESTADISTICAS: SE ACTIVA DESPUÉS DE REALIZAR UNA INSERCIÓN EN LA TABLA ESTADÍSTICAS Y REGISTRA EN LA TABLA LOG_MODIFICACIONES
-- EL NOMBRE DE LA TABLA, EL ID DEL REGISTRO INSERTADO, LA DESCRIPCIÓN DEL LA ACCION REALIZADA, EL USUARIO QUE REALIZÓ LA ACCIÓN Y LA FECHA Y HORA 
-- EN LA QUE SE REALIZÓ LA ACTUALIZACIÓN DE LA TABLA.
DROP TRIGGER IF EXISTS TRG_LOG_ESTADISTICAS_AFTER;
DELIMITER $$
CREATE TRIGGER TRG_LOG_ESTADISTICAS_AFTER
AFTER INSERT ON ESTADISTICAS
FOR EACH ROW
BEGIN
    INSERT INTO LOG_MODIFICACIONES (NOMBRE_TABLA, ID_REGISTRO, DESCRIPCION_ACTUAL, USUARIO_MODIFICADOR, FECHA_MODIFICACION, HORA_MODIFICACION)
    VALUES ('ESTADISTICAS', NEW.ID_ESTADISTICA, 'Nueva estadística insertada', USER(), CURDATE(), CURTIME());
END;
$$
DELIMITER ;

-- Inserción en ESTADISTICAS
INSERT INTO ESTADISTICAS (PROMEDIO, TOTAL) VALUES (5.0, '01:30:00');
INSERT INTO ESTADISTICAS (PROMEDIO, TOTAL) VALUES (7.0, '01:50:00');

SELECT * FROM LOG_INSERCIONES;
SELECT * FROM LOG_MODIFICACIONES;
SELECT * FROM ESTADISTICAS; 

-- TRIGGER BEFORE PARA MEDITACIONES: SE ACTIVA ANTES DE REALIZAR UNA ACTUALIZACIÓN EN LA TABLA MEDITACIONES Y REGISTRA EN LA TABLA LOG_MODIFICACIONES
-- EL NOMBRE DE LA TABLA, EL ID DEL REGISTRO MODIFICADO, LA DESCRIPCIÓN ANTERIOR (EN CASO DE SER NULO COLOCA DESCRIPCION ANTERIOR NO DISPONIBLE),
-- EL USUARIO QUE REALIZÓ LA ACCIÓN Y LA FECHA Y HORA EN LA QUE SE REALIZÓ LA MODIFICACIÓN DE LA TABLA.
DROP TRIGGER IF EXISTS TRG_LOG_MEDITACIONES_BEFORE;
DELIMITER $$
CREATE TRIGGER TRG_LOG_MEDITACIONES_BEFORE
BEFORE UPDATE ON MEDITACIONES
FOR EACH ROW
BEGIN
    DECLARE descripcion_anterior VARCHAR(255);

    -- Verificar si la descripción anterior es NULL
    IF OLD.DESCRIPCION IS NULL THEN
        SET descripcion_anterior = 'Descripción anterior no disponible';
    ELSE
        SET descripcion_anterior = CONCAT('Descripción anterior: ', OLD.DESCRIPCION);
    END IF;

    INSERT INTO LOG_MODIFICACIONES (NOMBRE_TABLA, ID_REGISTRO, DESCRIPCION_ANTERIOR, USUARIO_MODIFICADOR, FECHA_MODIFICACION, HORA_MODIFICACION)
    VALUES ('MEDITACIONES', OLD.ID_MEDITACION, descripcion_anterior, USER(), CURDATE(), CURTIME());
END;
$$
DELIMITER ;

-- TRIGGER AFTER PARA MEDITACIONES: SE ACTIVA DESPUÉS DE REALIZAR UNA ACTUALIZACIÓN EN LA TABLA MEDITACIONES Y REGISTRA EN LA TABLA LOG_MODIFICACIONES
-- EL NOMBRE DE LA TABLA, EL ID DEL REGISTRO MODIFICADO, LA DESCRIPCIÓN ACTUAL, EL USUARIO QUE REALIZÓ LA ACCIÓN Y LA FECHA Y HORA EN LA QUE SE REALIZÓ
-- LA MODIFICACIÓN DE LA TABLA.
DROP TRIGGER IF EXISTS TRG_LOG_MEDITACIONES_AFTER;
DELIMITER $$
CREATE TRIGGER TRG_LOG_MEDITACIONES_AFTER
AFTER UPDATE ON MEDITACIONES
FOR EACH ROW
BEGIN
    INSERT INTO LOG_MODIFICACIONES (NOMBRE_TABLA, ID_REGISTRO, DESCRIPCION_ACTUAL, USUARIO_MODIFICADOR, FECHA_MODIFICACION, HORA_MODIFICACION)
    VALUES ('MEDITACIONES', NEW.ID_MEDITACION, CONCAT('Nueva descripción: ', NEW.DESCRIPCION), USER(), CURDATE(), CURTIME());
END;
$$
DELIMITER ;
-- Actualización en MEDITACIONES
UPDATE MEDITACIONES SET DESCRIPCION = 'Meditación para ayudar a conciliar el sueño toda la noche' WHERE ID_MEDITACION = 2;
SELECT * FROM LOG_INSERCIONES;
SELECT * FROM LOG_MODIFICACIONES;
SELECT * FROM MEDITACIONES; 
 